# Form implementation generated from reading ui file 'QtCountdownWindow.ui'
#
# Created by: PyQt6 UI code generator 6.6.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(765, 509)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(Dialog)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.verticalLayout1 = QtWidgets.QVBoxLayout()
        self.verticalLayout1.setObjectName("verticalLayout1")
        self.verticalLayout2 = QtWidgets.QVBoxLayout()
        self.verticalLayout2.setObjectName("verticalLayout2")
        self.horizontalLayout1 = QtWidgets.QHBoxLayout()
        self.horizontalLayout1.setObjectName("horizontalLayout1")
        self.lcdHours = QtWidgets.QLCDNumber(parent=Dialog)
        self.lcdHours.setDigitCount(2)
        self.lcdHours.setObjectName("lcdHours")
        self.horizontalLayout1.addWidget(self.lcdHours)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Maximum, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout1.addItem(spacerItem)
        self.lcdMinutes = QtWidgets.QLCDNumber(parent=Dialog)
        self.lcdMinutes.setDigitCount(2)
        self.lcdMinutes.setObjectName("lcdMinutes")
        self.horizontalLayout1.addWidget(self.lcdMinutes)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Maximum, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout1.addItem(spacerItem1)
        self.lcdSeconds = QtWidgets.QLCDNumber(parent=Dialog)
        self.lcdSeconds.setFocusPolicy(QtCore.Qt.FocusPolicy.NoFocus)
        self.lcdSeconds.setDigitCount(2)
        self.lcdSeconds.setObjectName("lcdSeconds")
        self.horizontalLayout1.addWidget(self.lcdSeconds)
        self.verticalLayout2.addLayout(self.horizontalLayout1)
        self.verticalLayout1.addLayout(self.verticalLayout2)
        self.labelUserNotice = QtWidgets.QLabel(parent=Dialog)
        self.labelUserNotice.setMaximumSize(QtCore.QSize(16777215, 100))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.labelUserNotice.setFont(font)
        self.labelUserNotice.setStyleSheet("")
        self.labelUserNotice.setObjectName("labelUserNotice")
        self.verticalLayout1.addWidget(self.labelUserNotice, 0, QtCore.Qt.AlignmentFlag.AlignHCenter)
        self.verticalLayout_2.addLayout(self.verticalLayout1)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.labelUserNotice.setText(_translate("Dialog", "Close this window to cancel the countdown\n"
"Minimize to run the countdown in the background."))
